template = "https://github.com/giellalt/template-lang-und"
rev_id = 233
template_sha = "4712e7cbb43166fccf1100b5e6791c0f3de2f261"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-inp"
__UND2C__ = "inp"
__UNDEFINED__ = "IÃ±apari"
__UND__ = "inp"
