template = ""
rev_id = 193
template_sha = "0bd8270e3c0fbfa76e8f7b302ccf23650257f9a8"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-inp"
__UND2C__ = "inp"
__UNDEFINED__ = "IÃ±apari"
__UND__ = "inp"
