template = ""
rev_id = 116
template_sha = "b5ca8d53a8f7930e16274fc911f264d28407bf62"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-inp"
__UND2C__ = "inp"
__UNDEFINED__ = "IÃ±apari"
__UND__ = "inp"
