template = ""
rev_id = 107
template_sha = "2f2f1f21a10b56b75f0c8afcf409f313674887bc"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-inp"
__UND2C__ = "inp"
__UNDEFINED__ = "IÃ±apari"
__UND__ = "inp"
