template = ""
rev_id = 151
template_sha = "52213ce4ca8d6057a7e2ada1b6e2b79a11ebd004"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-inp"
__UND2C__ = "inp"
__UNDEFINED__ = "IÃ±apari"
__UND__ = "inp"
