template = ""
rev_id = 134
template_sha = "32303884fdd872b2729f81481178a531f91eeabc"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-inp"
__UND2C__ = "inp"
__UNDEFINED__ = "IÃ±apari"
__UND__ = "inp"
