template = "https://github.com/giellalt/template-lang-und"
rev_id = 275
template_sha = "ae7f0a90eca4365746c3ec57f8e39437abd6d807"

[replacements]
__GLOTTOLOG_ID__ = "inap1242"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-inp"
__UND2C__ = "inp"
__UNDEFINED__ = "IÃ±apari"
__UND__ = "inp"
