template = "https://github.com/giellalt/template-lang-und"
rev_id = 210
template_sha = "70467e07657f5fc8727ee9455a0f40101acbe30a"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-inp"
__UND2C__ = "inp"
__UNDEFINED__ = "IÃ±apari"
__UND__ = "inp"
