template = "https://github.com/giellalt/template-lang-und"
rev_id = 220
template_sha = "fc1c7834dc256556d974344d74d3d0d74323a4f5"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-inp"
__UND2C__ = "inp"
__UNDEFINED__ = "IÃ±apari"
__UND__ = "inp"
