template = ""
rev_id = 111
template_sha = "d59ead324f93a11c1a6fe6fc0f9da3698f299dca"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-inp"
__UND2C__ = "inp"
__UNDEFINED__ = "IÃ±apari"
__UND__ = "inp"
